#!/usr/bin/env bash
#
# gen-ecosystem-table.sh — Generate the 8-category Ecosystem CI Status board.
#
# For every repo referenced as a submodule in .gitmodules (plus Odysseus itself),
# this script reads the check-runs emitted on the default branch, maps each to one
# of the 8 canonical categories, and emits a Markdown table with one shields.io
# per-check-run badge per present category. Categories with no matching check are
# marked as a gap (linking a tracking issue when GAP_ISSUES provides one).
#
# Canonical categories (see docs/ci-naming-convention.md):
#   build · test · lint · package · install · release · security · custom
#
# The table is auto-derived so it never drifts from the repos' real CI.
#
# Requires the `gh` CLI authenticated with org read access.
#
# Usage:
#   gen-ecosystem-table.sh                 Print the table to stdout.
#   gen-ecosystem-table.sh --output PATH   Also write the table to PATH.
#   gen-ecosystem-table.sh --inject README.md
#                                          Replace the block between the
#                                          <!-- ECOSYSTEM-CI-TABLE:START --> and
#                                          <!-- ECOSYSTEM-CI-TABLE:END --> markers
#                                          in README.md with the generated table.
#
set -uo pipefail

ORG="HomericIntelligence"
OUTPUT_PATH=""
INJECT_PATH=""

while [ $# -gt 0 ]; do
  case "$1" in
    --output) OUTPUT_PATH="${2:-}"; [ -z "$OUTPUT_PATH" ] && { echo "error: --output requires a path" >&2; exit 2; }; shift 2 ;;
    --inject) INJECT_PATH="${2:-}"; [ -z "$INJECT_PATH" ] && { echo "error: --inject requires a path" >&2; exit 2; }; shift 2 ;;
    -h|--help) sed -n '2,30p' "$0" | sed 's/^# \{0,1\}//'; exit 0 ;;
    *) echo "error: unknown argument: $1" >&2; exit 2 ;;
  esac
done

command -v gh >/dev/null 2>&1 || { echo "error: gh CLI not found" >&2; exit 2; }

REPO_ROOT="$(git rev-parse --show-toplevel 2>/dev/null)" || { echo "error: not in a git repo" >&2; exit 2; }
GITMODULES="$REPO_ROOT/.gitmodules"
[ -f "$GITMODULES" ] || { echo "error: $GITMODULES not found" >&2; exit 2; }

# org/repo list: Odysseus itself first, then every submodule.
mapfile -t SUBS < <(
  git config --file "$GITMODULES" --get-regexp 'submodule\..*\.url' \
    | awk '{print $2}' | sed -E 's#\.git$##; s#^https://github.com/##; s#^git@github.com:##'
)
REPOS=("$ORG/Odysseus" "${SUBS[@]}")

CATEGORIES=(build test lint package install release security custom)

# Map an emitted check-run name to a canonical category (echoes the category, or
# empty if it belongs to "custom"/unmatched). Order matters: most specific first.
classify() {
  local n="$1"
  shopt -s nocasematch
  case "$n" in
    security/*|*codeql*|*"analyze ("*|*gitleaks*|*trivy*|*semgrep*|*dependency*scan*|*secrets*scan*|*sast*) echo security ;;
    release|release-please|"release please"|*publish*) echo release ;;
    install|install-test|*install*smoke*|*install*verify*) echo install ;;
    package|*sdist*|*wheel*|*sbom*|*container*image*|*"build, scan, and push"*) echo package ;;
    build|idempotent-build|build-test|"build & test"|build*) echo build ;;
    test|unit-tests|integration-tests|bats|*tests|*test) echo test ;;
    lint|markdownlint|hadolint|*lint*|ruff|shellcheck|forbid-suppressions|justfile-check) echo lint ;;
    *) echo "" ;;  # unmatched -> custom
  esac
  shopt -u nocasematch
}

badge() { # repo canonical-name label
  local repo="$1" name="$2" label="$3" enc
  enc=$(printf '%s' "$name" | sed 's/ /%20/g; s#/#%2F#g')
  local lbl; lbl=$(printf '%s' "$label" | sed 's/ /%20/g')
  printf '[![%s](https://img.shields.io/github/check-runs/%s/main?nameFilter=%s&label=%s)](https://github.com/%s/actions)' \
    "$label" "$repo" "$enc" "$lbl" "$repo"
}

report=""
append() { report+="$1"$'\n'; }

append "## Ecosystem CI Status"
append ""
append "> Auto-generated by \`scripts/gen-ecosystem-table.sh\` — do not edit by hand."
append "> Each cell shows the live status of that repo's canonical CI category (see"
append "> [docs/ci-naming-convention.md](docs/ci-naming-convention.md)). A 🔗 links the tracking"
append "> issue for a category the repo does not yet emit."
append ""
append "| Repository | Build | Test | Lint | Package | Install | Release | Security | Custom |"
append "|------------|-------|------|------|---------|---------|---------|----------|--------|"

for repo in "${REPOS[@]}"; do
  short="${repo#"$ORG"/}"
  branch=$(gh repo view "$repo" --json defaultBranchRef --jq '.defaultBranchRef.name' 2>/dev/null || echo main)
  [ -z "$branch" ] && branch=main
  sha=$(gh api "repos/$repo/commits/$branch" --jq .sha 2>/dev/null)
  mapfile -t names < <(gh api "repos/$repo/commits/$sha/check-runs?per_page=100" --jq '[.check_runs[].name]|unique|.[]' 2>/dev/null)

  # bucket names by category
  declare -A first=()    # canonical name to badge per category (first match wins)
  customs=()
  for n in "${names[@]}"; do
    cat=$(classify "$n")
    if [ -z "$cat" ]; then customs+=("$n"); continue; fi
    [ -z "${first[$cat]:-}" ] && first[$cat]="$n"
  done

  row="| [$short](https://github.com/$repo) |"
  for cat in build test lint package install release security; do
    if [ -n "${first[$cat]:-}" ]; then
      row+=" $(badge "$repo" "${first[$cat]}" "$cat") |"
    else
      # gap: link tracking issue if provided via GAP_ISSUES env (repo:cat=url,...)
      url=""
      if [ -n "${GAP_ISSUES:-}" ]; then
        url=$(printf '%s' "$GAP_ISSUES" | tr ',' '\n' | sed -n "s#^${short}:${cat}=##p" | head -1)
      fi
      if [ -n "$url" ]; then row+=" [🔗 planned]($url) |"; else row+=" — |"; fi
    fi
  done
  # custom cell: comma-joined leftover check names (or em dash)
  if [ "${#customs[@]}" -gt 0 ]; then
    IFS=', ' ; row+=" $(printf '%s' "$(IFS=', '; echo "${customs[*]}")" | sed 's/, /, /g') |" ; unset IFS
  else
    row+=" — |"
  fi
  append "$row"
  unset first customs
done

append ""
append "> Generated $(date -u +%Y-%m-%dT%H:%M:%SZ)."

if [ -n "$OUTPUT_PATH" ]; then printf '%s' "$report" > "$OUTPUT_PATH"; fi
if [ -n "$INJECT_PATH" ]; then
  [ -f "$INJECT_PATH" ] || { echo "error: $INJECT_PATH not found" >&2; exit 2; }
  awk -v repl="$report" '
    /<!-- ECOSYSTEM-CI-TABLE:START -->/ { print; print repl; skip=1; next }
    /<!-- ECOSYSTEM-CI-TABLE:END -->/   { skip=0 }
    !skip { print }
  ' "$INJECT_PATH" > "$INJECT_PATH.tmp" && mv "$INJECT_PATH.tmp" "$INJECT_PATH"
fi
printf '%s' "$report"
