#!/usr/bin/env python3
"""Install configured pre-commit hooks through one isolated boundary."""

import argparse
import ctypes
import errno
import fcntl
import hashlib
import math
import os
import re
import resource
import secrets
import select
import selectors
import shlex
import signal
import stat
import subprocess
import sys
import tempfile
import time
from dataclasses import dataclass


HOOK_TYPES = (
    "commit-msg",
    "post-checkout",
    "post-commit",
    "post-merge",
    "post-rewrite",
    "pre-commit",
    "pre-merge-commit",
    "pre-push",
    "pre-rebase",
    "prepare-commit-msg",
)
HEADER = (
    "#!/usr/bin/env bash",
    "# File generated by pre-commit: https://pre-commit.com",
    "# ID: 138fd403232d2ddd5efb44317e38bf03",
    "",
    "# start templated",
)
TAIL = (
    "# end templated",
    "",
    'HERE="$(cd "$(dirname "$0")" && pwd)"',
    'ARGS+=(--hook-dir "$HERE" -- "$@")',
    "",
    'if [ -x "$INSTALL_PYTHON" ]; then',
    '    exec "$INSTALL_PYTHON" -mpre_commit "${ARGS[@]}"',
    "elif command -v pre-commit > /dev/null; then",
    '    exec pre-commit "${ARGS[@]}"',
    "else",
    "    echo '`pre-commit` not found.  Did you forget to activate your virtualenv?' 1>&2",
    "    exit 1",
    "fi",
)
READ_FLAGS = os.O_RDONLY | os.O_CLOEXEC | os.O_NOFOLLOW | os.O_NONBLOCK
DIR_FLAGS = os.O_RDONLY | os.O_CLOEXEC | os.O_NOFOLLOW | os.O_DIRECTORY
VERSION = re.compile(r"pre-commit ([0-9]+\.[0-9]+(?:\.[0-9]+)?)")
MAX_TOOL_BYTES = 256 * 1024 * 1024


class SetupError(RuntimeError):
    pass


class CancellationError(SetupError):
    """A host signal cancelled the current helper operation."""

    def __init__(self, signum):
        self.signum = signum
        super().__init__("command cancelled by {}".format(signal.Signals(signum).name))


def emit(kind, message):
    print("{}\t{}".format(kind, str(message).replace("\n", " ")))


def ident(value):
    return (
        value.st_dev,
        value.st_ino,
        value.st_mode,
        value.st_uid,
        value.st_gid,
        value.st_nlink,
        value.st_size,
        value.st_mtime_ns,
        value.st_ctime_ns,
    )


def dir_ident(value):
    return (value.st_dev, value.st_ino, value.st_mode, value.st_uid, value.st_gid)


def read_fd(descriptor, limit=4 * 1024 * 1024):
    os.lseek(descriptor, 0, os.SEEK_SET)
    result = bytearray()
    while True:
        chunk = os.read(descriptor, min(65536, limit + 1 - len(result)))
        if not chunk:
            return bytes(result)
        result.extend(chunk)
        if len(result) > limit:
            raise SetupError("file exceeds the allowed size")


def write_all(descriptor, data):
    view = memoryview(data)
    while view:
        written = os.write(descriptor, view)
        if written <= 0:
            raise SetupError("write made no progress")
        view = view[written:]


@dataclass
class BoundFile:
    path: str
    token: tuple
    data: bytes
    executable: bool
    directory_fd: int = None

    @classmethod
    def open(cls, path, executable=None, directory_fd=None):
        try:
            named = os.stat(path, dir_fd=directory_fd, follow_symlinks=False)
            descriptor = os.open(path, READ_FLAGS, dir_fd=directory_fd)
        except OSError as error:
            raise SetupError("cannot bind {}: {}".format(path, error))
        try:
            opened = os.fstat(descriptor)
            if ident(named) != ident(opened) or not stat.S_ISREG(opened.st_mode):
                raise SetupError("{} is not a direct regular file".format(path))
            if opened.st_nlink != 1 or opened.st_uid != os.geteuid():
                raise SetupError("{} has an unsafe owner or link count".format(path))
            data = read_fd(descriptor)
            after = os.fstat(descriptor)
            named_after = os.stat(path, dir_fd=directory_fd, follow_symlinks=False)
            if ident(opened) != ident(after) or ident(after) != ident(named_after):
                raise SetupError("{} changed while reading".format(path))
            is_executable = bool(after.st_mode & 0o111)
            if executable is not None and executable != is_executable:
                raise SetupError("{} has an invalid executable mode".format(path))
            return cls(path, ident(after), data, is_executable, directory_fd)
        finally:
            os.close(descriptor)

    def verify(self):
        current = BoundFile.open(self.path, directory_fd=self.directory_fd)
        if current.token != self.token or current.data != self.data:
            raise SetupError("{} changed after binding".format(self.path))


@dataclass
class BoundTool:
    path: str
    token: tuple
    descriptor: int

    @classmethod
    def open(cls, path):
        descriptor = None
        try:
            named = os.lstat(path)
            descriptor = os.open(path, READ_FLAGS)
        except OSError as error:
            raise SetupError("cannot bind executable {}: {}".format(path, error))
        try:
            opened = os.fstat(descriptor)
            if (
                ident(named) != ident(opened)
                or not stat.S_ISREG(opened.st_mode)
                or opened.st_uid not in (0, os.geteuid())
                or not opened.st_mode & 0o111
                or opened.st_size > MAX_TOOL_BYTES
            ):
                raise SetupError("unsafe executable: {}".format(path))
            result = cls(path, ident(opened), descriptor)
            descriptor = None
            return result
        finally:
            if descriptor is not None:
                os.close(descriptor)

    def verify(self):
        if self.descriptor < 0:
            raise SetupError("executable binding is closed: {}".format(self.path))
        try:
            named = os.lstat(self.path)
            opened = os.fstat(self.descriptor)
        except OSError as error:
            raise SetupError(
                "cannot verify executable {}: {}".format(self.path, error)
            ) from error
        if ident(named) != self.token or ident(opened) != self.token:
            raise SetupError("executable changed after binding: {}".format(self.path))

    def read_prefix(self, limit=4096):
        if self.descriptor < 0:
            raise SetupError("executable binding is closed: {}".format(self.path))
        return os.pread(self.descriptor, limit, 0)

    def trusted_system_route(self):
        if (
            os.geteuid() == 0
            or self.token[3] != 0
            or stat.S_IMODE(self.token[2]) & 0o022
            or os.path.realpath(self.path) != os.path.abspath(self.path)
            or os.access(self.path, os.W_OK)
        ):
            return False
        current = os.path.dirname(self.path)
        while True:
            try:
                item = os.lstat(current)
            except OSError:
                return False
            if (
                not stat.S_ISDIR(item.st_mode)
                or item.st_uid != 0
                or stat.S_IMODE(item.st_mode) & 0o022
                or os.access(current, os.W_OK)
            ):
                return False
            parent = os.path.dirname(current)
            if parent == current:
                return True
            current = parent

    def snapshot(self, tree, name):
        if (
            not name
            or name in (".", "..")
            or os.sep in name
            or (os.altsep is not None and os.altsep in name)
        ):
            raise SetupError("invalid executable snapshot name")
        tree.verify()
        self.verify()
        flags = os.O_WRONLY | os.O_CREAT | os.O_EXCL | os.O_CLOEXEC | os.O_NOFOLLOW
        descriptor = os.open(name, flags, 0o600, dir_fd=tree.root.descriptor)
        total = 0
        try:
            os.lseek(self.descriptor, 0, os.SEEK_SET)
            while True:
                chunk = os.read(self.descriptor, 65536)
                if not chunk:
                    break
                total += len(chunk)
                if total > MAX_TOOL_BYTES:
                    raise SetupError("executable exceeds the allowed size")
                write_all(descriptor, chunk)
            if total != self.token[6]:
                raise SetupError("executable changed while snapshotting")
            os.fsync(descriptor)
            os.fchmod(descriptor, 0o500)
            os.fsync(descriptor)
            copied = os.fstat(descriptor)
            if (
                not stat.S_ISREG(copied.st_mode)
                or copied.st_uid != os.geteuid()
                or copied.st_nlink != 1
                or stat.S_IMODE(copied.st_mode) != 0o500
                or copied.st_size != total
            ):
                raise SetupError("unsafe executable snapshot")
        finally:
            os.close(descriptor)
        self.verify()
        tree.verify()
        result = BoundTool.open(os.path.join(tree.path, name))
        if (
            result.token[3] != os.geteuid()
            or result.token[5] != 1
            or stat.S_IMODE(result.token[2]) != 0o500
            or result.token[6] != total
        ):
            result.close()
            raise SetupError("unsafe executable snapshot")
        return result

    def close(self):
        descriptor = self.descriptor
        if descriptor < 0:
            return
        self.descriptor = -1
        os.close(descriptor)


class ReadOnlyExecutionBoundary:
    """Run tools with a read-only host and one private writable tree."""

    def __init__(self, tree, data_tree, bound_tools):
        self.tree = tree
        self.data_tree = data_tree
        self.bound_tools = bound_tools
        self.guard = None
        self.kind = None

    def require(self):
        if self.guard is not None:
            return
        if sys.platform.startswith("linux"):
            candidates = (
                ("bubblewrap", "/usr/bin/bwrap"),
                ("bubblewrap", "/bin/bwrap"),
            )
        else:
            raise SetupError(
                "no secure execution boundary is available on this platform"
            )
        for kind, path in candidates:
            try:
                guard = BoundTool.open(path)
            except SetupError:
                continue
            if guard.trusted_system_route():
                self.kind = kind
                self.guard = guard
                self.bound_tools.append(guard)
                return
            guard.close()
        raise SetupError(
            "no trusted secure execution boundary is available on this platform"
        )

    def verify(self):
        self.tree.verify()
        self.data_tree.verify()
        if self.guard is not None:
            self.guard.verify()

    @staticmethod
    def _parent_directories(path):
        result = []
        current = os.path.dirname(path)
        while current not in ("", os.sep, "/tmp"):
            result.append(current)
            current = os.path.dirname(current)
        return list(reversed(result))

    def wrap(self, command, cwd="/", readonly_paths=()):
        if self.guard is None:
            return list(command), command[0]
        self.verify()
        if self.kind == "bubblewrap":
            directory_args = []
            for path in (self.tree.path, self.data_tree.path, *readonly_paths):
                for parent in self._parent_directories(path):
                    if parent not in directory_args:
                        directory_args.extend(("--dir", parent))
            system_args = []
            if os.path.isdir("/etc/alternatives"):
                system_args.extend(
                    (
                        "--dir",
                        "/etc",
                        "--ro-bind",
                        "/etc/alternatives",
                        "/etc/alternatives",
                    )
                )
            return (
                [
                    self.guard.path,
                    "--die-with-parent",
                    "--unshare-user",
                    "--disable-userns",
                    "--unshare-pid",
                    "--unshare-net",
                    "--unshare-ipc",
                    "--new-session",
                    "--cap-drop",
                    "ALL",
                    "--ro-bind",
                    "/usr",
                    "/usr",
                    "--symlink",
                    "usr/bin",
                    "/bin",
                    "--symlink",
                    "usr/sbin",
                    "/sbin",
                    "--symlink",
                    "usr/lib",
                    "/lib",
                    "--proc",
                    "/proc",
                    "--dev",
                    "/dev",
                    "--tmpfs",
                    "/tmp",
                ]
                + system_args
                + directory_args
                + [
                    "--ro-bind",
                    self.tree.path,
                    self.tree.path,
                    "--bind",
                    self.data_tree.path,
                    self.data_tree.path,
                ]
                + [
                    value
                    for path in readonly_paths
                    for value in ("--ro-bind", path, path)
                ]
                + [
                    "--chdir",
                    cwd,
                    "--",
                ]
                + list(command),
                self.guard.path,
            )
        raise SetupError("invalid read-only executable boundary")


class BoundExecutable(str):
    """Keep the operator-selected argv path and a private execution route."""

    def __new__(
        cls,
        source,
        execution,
        boundary,
        interpreter_source=None,
        interpreter_execution=None,
        dependencies=(),
    ):
        value = super().__new__(cls, source.path)
        value.source = source
        value.execution = execution
        value.boundary = boundary
        value.interpreter_source = interpreter_source
        value.interpreter_execution = interpreter_execution
        value.dependencies = tuple(dependencies)
        return value


@dataclass
class BoundDir:
    path: str
    descriptor: int
    token: tuple
    parent_fd: int = None
    name: str = None

    @staticmethod
    def _check(path, named, opened, safe, shared_temp=False):
        if dir_ident(named) != dir_ident(opened):
            raise SetupError("unsafe directory binding: {}".format(path))
        mode = stat.S_IMODE(opened.st_mode)
        if shared_temp:
            owner_is_safe = (opened.st_uid == os.geteuid() and not mode & 0o022) or (
                opened.st_uid == 0 and mode == 0o1777
            )
        else:
            owner_is_safe = opened.st_uid == os.geteuid()
        if not owner_is_safe:
            raise SetupError("unsafe directory owner: {}".format(path))
        if safe and mode & 0o022:
            raise SetupError(
                "directory is writable by another user class: {}".format(path)
            )

    @classmethod
    def open(cls, path, safe=False, shared_temp=False):
        if os.path.realpath(path) != os.path.abspath(path):
            raise SetupError("{} contains a symbolic path component".format(path))
        try:
            named = os.lstat(path)
            descriptor = os.open(path, DIR_FLAGS)
        except OSError as error:
            raise SetupError("cannot bind {}: {}".format(path, error))
        try:
            opened = os.fstat(descriptor)
            cls._check(path, named, opened, safe, shared_temp)
        except BaseException:
            os.close(descriptor)
            raise
        return cls(path, descriptor, dir_ident(opened))

    @classmethod
    def open_at(cls, parent_fd, name, path, safe=True):
        try:
            named = os.stat(name, dir_fd=parent_fd, follow_symlinks=False)
            descriptor = os.open(name, DIR_FLAGS, dir_fd=parent_fd)
        except OSError as error:
            raise SetupError("cannot bind {}: {}".format(path, error))
        try:
            opened = os.fstat(descriptor)
            cls._check(path, named, opened, safe)
        except BaseException:
            os.close(descriptor)
            raise
        return cls(path, descriptor, dir_ident(opened), parent_fd, name)

    def verify(self):
        named = (
            os.stat(self.name, dir_fd=self.parent_fd, follow_symlinks=False)
            if self.parent_fd is not None
            else os.lstat(self.path)
        )
        if (
            dir_ident(os.fstat(self.descriptor)) != self.token
            or dir_ident(named) != self.token
        ):
            raise SetupError("directory changed after binding: {}".format(self.path))

    def close(self):
        descriptor = self.descriptor
        if descriptor < 0:
            return
        self.descriptor = -1
        os.close(descriptor)


def clean_env(pre_commit, git, home, cache):
    def execution_directory(command):
        execution = getattr(command, "execution", None)
        return os.path.dirname(
            execution.path if execution is not None else os.fspath(command)
        )

    paths = []
    for path in (
        execution_directory(pre_commit),
        execution_directory(git),
        "/usr/bin",
        "/bin",
    ):
        if path not in paths:
            paths.append(path)
    return {
        "GIT_CONFIG_GLOBAL": "/dev/null",
        "GIT_CONFIG_NOSYSTEM": "1",
        "HOME": home,
        "LANG": "C",
        "LC_ALL": "C",
        "PATH": os.pathsep.join(paths),
        "PRE_COMMIT_HOME": cache,
        "PYTHONNOUSERSITE": "1",
        "TMPDIR": home,
    }


class LeaderObserver:
    """Observe a child exit without releasing its process identifier."""

    def __init__(self, pid):
        self.pid = pid
        self.queue = None
        self.seen = False
        if all(
            hasattr(os, name)
            for name in ("waitid", "P_PID", "WEXITED", "WNOHANG", "WNOWAIT")
        ):
            self.kind = "waitid"
            return
        if (
            sys.platform == "darwin"
            and hasattr(select, "kqueue")
            and all(
                hasattr(select, name)
                for name in (
                    "KQ_FILTER_PROC",
                    "KQ_EV_ADD",
                    "KQ_EV_ENABLE",
                    "KQ_NOTE_EXIT",
                )
            )
        ):
            self.kind = "kqueue"
            self.queue = select.kqueue()
            event = select.kevent(
                pid,
                filter=select.KQ_FILTER_PROC,
                flags=select.KQ_EV_ADD | select.KQ_EV_ENABLE,
                fflags=select.KQ_NOTE_EXIT,
            )
            try:
                self.queue.control([event], 0, 0)
            except BaseException:
                self.queue.close()
                self.queue = None
                raise
            return
        raise SetupError(
            "this platform cannot observe a child without reaping it safely"
        )

    def exited(self):
        if self.seen:
            return True
        if self.kind == "waitid":
            try:
                result = os.waitid(
                    os.P_PID,
                    self.pid,
                    os.WEXITED | os.WNOHANG | os.WNOWAIT,
                )
            except ChildProcessError as error:
                raise SetupError(
                    "child ownership was lost before process-group cleanup"
                ) from error
            self.seen = result is not None and getattr(result, "si_pid", 0) != 0
        else:
            self.seen = bool(self.queue.control(None, 1, 0))
        return self.seen

    def close(self):
        if self.queue is not None:
            self.queue.close()
            self.queue = None


def stop_group(process, observer=None, leader_exited=False):
    """Terminate the owned process group, then reap its leader exactly once."""

    # Popen(start_new_session=True) makes the child the group leader before
    # exec.  Keep the leader unreaped through both group signals.  Its process
    # identifier then cannot be reused as a different process-group identifier.
    for group_signal, grace in ((signal.SIGTERM, 0.25), (signal.SIGKILL, 0.05)):
        if observer is not None and not leader_exited:
            try:
                leader_exited = observer.exited()
            except SetupError:
                pass
        try:
            os.killpg(process.pid, group_signal)
        except PermissionError:
            # Darwin reports EPERM when the retained leader is a zombie and no
            # signalable member remains in its process group.  Accept that
            # result only after a non-reaping observer reported leader exit.
            if not leader_exited:
                raise
        except ProcessLookupError:
            pass
        deadline = time.monotonic() + grace
        while time.monotonic() < deadline:
            time.sleep(min(0.01, max(0, deadline - time.monotonic())))
    try:
        return process.wait(timeout=1.0)
    except subprocess.TimeoutExpired as error:
        raise SetupError(
            "child process could not be reaped after process-group cleanup"
        ) from error


def _child_resource_limits(timeout):
    requested = (
        (resource.RLIMIT_AS, 512 * 1024 * 1024),
        (resource.RLIMIT_CPU, min(4, max(1, math.ceil(timeout) + 1))),
        (resource.RLIMIT_NOFILE, 128),
        (resource.RLIMIT_FSIZE, 8 * 1024 * 1024),
        (resource.RLIMIT_CORE, 0),
    )
    if hasattr(resource, "RLIMIT_NPROC"):
        requested += ((resource.RLIMIT_NPROC, 512),)

    def apply():
        for key, wanted in requested:
            _soft, hard = resource.getrlimit(key)
            value = wanted if hard == resource.RLIM_INFINITY else min(wanted, hard)
            resource.setrlimit(key, (value, value))

    return apply


def run(argv, cwd, env, timeout):
    if not math.isfinite(timeout) or timeout <= 0:
        raise SetupError("timeout must be finite and positive")
    if signal.getsignal(signal.SIGCHLD) is not signal.SIG_DFL:
        raise SetupError(
            "SIGCHLD must use its default disposition before process creation"
        )
    previous_handlers = {}
    cancelled = [None]

    def cancel(signum, _frame):
        # Do not raise from a signal handler.  Popen can have created the child
        # before it returns the process object to this frame.
        if cancelled[0] is None:
            cancelled[0] = signum

    process = None
    observer = None
    reaped = False
    selector = selectors.DefaultSelector()
    buffers = {"out": bytearray(), "err": bytearray()}
    deadline = time.monotonic() + timeout
    bound = argv[0] if isinstance(argv[0], BoundExecutable) else None

    def cancellation_error():
        if cancelled[0] is None:
            return None
        return CancellationError(cancelled[0])

    def receive_ready(wait):
        for key, _ in selector.select(wait):
            try:
                chunk = os.read(key.fileobj.fileno(), 65536)
            except BlockingIOError:
                continue
            if not chunk:
                selector.unregister(key.fileobj)
                key.fileobj.close()
                continue
            buffers[key.data].extend(chunk)
            if len(buffers[key.data]) > 1024 * 1024:
                raise SetupError("command output exceeded the allowed size")

    try:
        try:
            for signum in (signal.SIGTERM, signal.SIGHUP, signal.SIGINT):
                previous_handlers[signum] = signal.getsignal(signum)
                signal.signal(signum, cancel)
        except ValueError:
            previous_handlers = {}

        problem = cancellation_error()
        if problem is not None:
            raise problem
        popen_kwargs = {
            "cwd": cwd,
            "env": env,
            "close_fds": True,
            "preexec_fn": _child_resource_limits(timeout),
            "stdin": subprocess.DEVNULL,
            "stdout": subprocess.PIPE,
            "stderr": subprocess.PIPE,
            "start_new_session": True,
        }
        command = argv
        if bound is not None:
            bound.source.verify()
            bound.execution.verify()
            for source_dependency, execution_dependency in bound.dependencies:
                source_dependency.verify()
                execution_dependency.verify()
            executable = bound.execution
            target_command = [bound.execution.path] + list(argv[1:])
            if bound.interpreter_source is not None:
                bound.interpreter_source.verify()
                bound.interpreter_execution.verify()
                target_command = [
                    bound.interpreter_execution.path,
                    bound.execution.path,
                ] + list(argv[1:])
                executable = bound.interpreter_execution
            if bound.boundary.guard is not None:
                readonly_paths = ()
                if (
                    len(argv) >= 3
                    and argv[1] == "-C"
                    and os.path.isabs(os.fspath(argv[2]))
                    and not os.path.commonpath(
                        (bound.boundary.data_tree.path, os.fspath(argv[2]))
                    )
                    == bound.boundary.data_tree.path
                ):
                    readonly_paths = (os.fspath(argv[2]),)
                command, executable_path = bound.boundary.wrap(
                    target_command, cwd, readonly_paths
                )
                executable = executable_path
                popen_kwargs["cwd"] = "/"
            popen_kwargs["env"] = dict(env)
            popen_kwargs["env"]["ODYSSEUS_EXECUTABLE_ORIGIN"] = bound.execution.path
            popen_kwargs["executable"] = (
                executable.path if isinstance(executable, BoundTool) else executable
            )
        process = subprocess.Popen(command, **popen_kwargs)
        problem = cancellation_error()
        if problem is not None:
            observer = LeaderObserver(process.pid)
            raise problem
        if deadline - time.monotonic() <= 0:
            raise SetupError("command timed out: {}".format(shlex.join(argv)))
        observer = LeaderObserver(process.pid)
        for stream, name in ((process.stdout, "out"), (process.stderr, "err")):
            os.set_blocking(stream.fileno(), False)
            selector.register(stream, selectors.EVENT_READ, name)

        while True:
            problem = cancellation_error()
            if problem is not None:
                raise problem
            remaining = deadline - time.monotonic()
            if remaining <= 0:
                raise SetupError("command timed out: {}".format(shlex.join(argv)))
            leader_exited = observer.exited()
            if leader_exited and not selector.get_map():
                break
            if selector.get_map():
                receive_ready(min(0.1, remaining))
            else:
                time.sleep(min(0.01, remaining))

        returncode = stop_group(process, observer=observer, leader_exited=True)
        reaped = True
        problem = cancellation_error()
        if problem is not None:
            raise problem
        # Read bytes that were in the pipes before the final group signal.
        while selector.get_map():
            before = len(selector.get_map())
            receive_ready(0)
            if len(selector.get_map()) == before:
                break
        problem = cancellation_error()
        if problem is not None:
            raise problem
        if bound is not None:
            bound.source.verify()
            bound.execution.verify()
            bound.boundary.verify()
            for source_dependency, execution_dependency in bound.dependencies:
                source_dependency.verify()
                execution_dependency.verify()
            if bound.interpreter_source is not None:
                bound.interpreter_source.verify()
                bound.interpreter_execution.verify()
        return returncode, bytes(buffers["out"]), bytes(buffers["err"])
    except BaseException as original_error:
        cleanup_error = None
        if process is not None and not reaped:
            observed_exit = False
            if observer is not None:
                try:
                    observed_exit = observer.exited()
                except SetupError:
                    observed_exit = False
            try:
                stop_group(process, observer=observer, leader_exited=observed_exit)
                reaped = True
            except BaseException as error:
                cleanup_error = error
        problem = cancellation_error()
        if problem is not None:
            raise problem from (cleanup_error or original_error)
        if cleanup_error is not None:
            raise cleanup_error from original_error
        raise
    finally:
        active_error = sys.exc_info()[1]
        final_cleanup_error = None
        if observer is not None:
            try:
                observer.close()
            except BaseException as error:
                final_cleanup_error = error
        try:
            selector.close()
        except BaseException as error:
            if final_cleanup_error is None:
                final_cleanup_error = error
        if process is not None:
            for stream in (process.stdout, process.stderr):
                if not stream.closed:
                    try:
                        stream.close()
                    except BaseException as error:
                        if final_cleanup_error is None:
                            final_cleanup_error = error
        final_problem = cancellation_error()
        for signum, handler in previous_handlers.items():
            try:
                signal.signal(signum, handler)
            except BaseException as error:
                if final_cleanup_error is None:
                    final_cleanup_error = error
        if final_problem is None:
            final_problem = cancellation_error()
        if final_problem is not None:
            if not isinstance(active_error, CancellationError):
                raise final_problem from (final_cleanup_error or active_error)
        elif final_cleanup_error is not None:
            raise final_cleanup_error from active_error


def require_ok(label, result):
    if result[0] != 0:
        detail = (result[2] or result[1]).decode("utf-8", "replace").strip()
        raise SetupError("{} failed{}".format(label, ": " + detail if detail else ""))


class PrivateTree:
    def __init__(self):
        base = os.path.realpath(tempfile.gettempdir())
        self.parent = None
        self.root = None
        self.name = ".odysseus-precommit-{}".format(secrets.token_hex(12))
        self.path = os.path.join(base, self.name)
        created = False
        try:
            self.parent = BoundDir.open(base, shared_temp=True)
            os.mkdir(self.name, 0o700, dir_fd=self.parent.descriptor)
            created = True
            self.root = BoundDir.open_at(
                self.parent.descriptor, self.name, self.path, safe=True
            )
        except BaseException as error:
            if self.root is not None:
                self.root.close()
                self.root = None
            if self.parent is not None:
                self.parent.close()
                self.parent = None
            if created:
                raise SetupError(
                    "private resource binding failed; preserved unbound route {}: {}".format(
                        self.path, error
                    )
                ) from error
            raise

    def mkdir(self, name):
        os.mkdir(name, 0o700, dir_fd=self.root.descriptor)
        path = os.path.join(self.path, name)
        child = BoundDir.open(path, safe=True)
        child.close()
        return path

    def verify(self):
        self.parent.verify()
        self.root.verify()

    @staticmethod
    def _cleanup_token(item):
        # Rename can change timestamps.  Device and inode identify the moved
        # object; mode and ownership retain the security properties needed for
        # recursive cleanup.
        return dir_ident(item)

    @staticmethod
    def _quarantine_name(descriptor):
        for _attempt in range(128):
            name = ".odysseus-quarantine-{}".format(secrets.token_hex(12))
            try:
                os.stat(name, dir_fd=descriptor, follow_symlinks=False)
            except FileNotFoundError:
                return name
        raise SetupError("cannot allocate a private cleanup quarantine name")

    @staticmethod
    def _restore_quarantine(descriptor, quarantine, name):
        try:
            atomic_rename(descriptor, quarantine, name)
        except SetupError:
            return quarantine
        return name

    def quarantine(self, descriptor, name, expected):
        quarantine = self._quarantine_name(descriptor)
        atomic_rename(descriptor, name, quarantine)
        try:
            moved = os.stat(quarantine, dir_fd=descriptor, follow_symlinks=False)
        except OSError as error:
            raise SetupError(
                "temporary entry disappeared after atomic quarantine; "
                "preserved route {}: {}".format(quarantine, error)
            ) from error
        if self._cleanup_token(moved) != expected:
            route = self._restore_quarantine(descriptor, quarantine, name)
            raise SetupError(
                "temporary entry changed at atomic quarantine; "
                "replacement preserved as {}".format(route)
            )
        return quarantine

    def clear(self, descriptor):
        for name in os.listdir(descriptor):
            item = os.stat(name, dir_fd=descriptor, follow_symlinks=False)
            expected = self._cleanup_token(item)
            quarantine = self.quarantine(descriptor, name, expected)
            if stat.S_ISDIR(item.st_mode):
                child = os.open(quarantine, DIR_FLAGS, dir_fd=descriptor)
                try:
                    if dir_ident(os.fstat(child)) != expected:
                        raise SetupError("temporary directory changed during cleanup")
                    self.clear(child)
                finally:
                    os.close(child)
                if (
                    dir_ident(
                        os.stat(quarantine, dir_fd=descriptor, follow_symlinks=False)
                    )
                    != expected
                ):
                    raise SetupError("temporary directory changed before cleanup")
                os.rmdir(quarantine, dir_fd=descriptor)
            else:
                current = os.stat(quarantine, dir_fd=descriptor, follow_symlinks=False)
                if self._cleanup_token(current) != expected:
                    raise SetupError("temporary entry changed before cleanup")
                os.unlink(quarantine, dir_fd=descriptor)

    def close(self):
        problem = None
        root_quarantine = None
        try:
            self.parent.verify()
            if dir_ident(os.fstat(self.root.descriptor)) != self.root.token:
                raise SetupError("temporary root descriptor changed before cleanup")
            root_quarantine = self.quarantine(
                self.parent.descriptor, self.name, self.root.token
            )
            self.clear(self.root.descriptor)
            named = os.stat(
                root_quarantine,
                dir_fd=self.parent.descriptor,
                follow_symlinks=False,
            )
            if dir_ident(named) != self.root.token:
                raise SetupError(
                    "temporary root changed after atomic quarantine; "
                    "replacement was preserved as {}".format(root_quarantine)
                )
            os.rmdir(root_quarantine, dir_fd=self.parent.descriptor)
            root_quarantine = None
        except (OSError, SetupError) as error:
            recovery = root_quarantine
            if root_quarantine is not None:
                recovery = self._restore_quarantine(
                    self.parent.descriptor, root_quarantine, self.name
                )
            problem = "cannot safely clean temporary resources"
            if recovery is not None:
                problem += "; preserved root as {}".format(recovery)
            problem += ": {}".format(error)
        self.root.close()
        self.parent.close()
        self.root = None
        self.parent = None
        return problem


class _SnapshotTarget:
    def __init__(self, directory):
        self.root = directory
        self.path = directory.path

    def verify(self):
        self.root.verify()


def _snapshot_sibling_closure(source, tree, name, bound_tools, boundary):
    """Copy direct regular siblings; unresolved subtrees then fail closed."""

    boundary.require()
    closure_path = tree.mkdir(name + "-runtime")
    closure = BoundDir.open(closure_path, safe=True)
    bound_tools.append(closure)
    target = _SnapshotTarget(closure)
    source_name = os.path.basename(source.path)
    execution = source.snapshot(target, source_name)
    bound_tools.append(execution)
    dependencies = []
    total = 0
    parent = BoundDir.open(os.path.dirname(source.path), safe=True)
    try:
        for sibling_name in sorted(os.listdir(parent.descriptor), key=os.fsencode):
            if sibling_name == source_name:
                continue
            try:
                item = os.stat(
                    sibling_name,
                    dir_fd=parent.descriptor,
                    follow_symlinks=False,
                )
            except OSError as error:
                raise SetupError("runtime sibling changed during inventory") from error
            if not stat.S_ISREG(item.st_mode):
                continue
            source_dependency = BoundFile.open(os.path.join(parent.path, sibling_name))
            total += len(source_dependency.data)
            if total > 64 * 1024 * 1024:
                raise SetupError("runtime sibling closure exceeds the allowed size")
            suffix = (
                sibling_name[len(source_name) :]
                if sibling_name.startswith(source_name)
                else None
            )
            destination_name = (
                source_name + suffix if suffix is not None else sibling_name
            )
            flags = os.O_WRONLY | os.O_CREAT | os.O_EXCL | os.O_CLOEXEC | os.O_NOFOLLOW
            descriptor = os.open(
                destination_name,
                flags,
                0o500 if source_dependency.executable else 0o400,
                dir_fd=closure.descriptor,
            )
            try:
                write_all(descriptor, source_dependency.data)
                os.fsync(descriptor)
            finally:
                os.close(descriptor)
            execution_dependency = BoundFile.open(
                os.path.join(closure.path, destination_name)
            )
            source_dependency.verify()
            dependencies.append((source_dependency, execution_dependency))
    finally:
        parent.close()
    closure.verify()
    return execution, tuple(dependencies)


def execution_tool(source, tree, name, bound_tools, boundary):
    if source.trusted_system_route():
        return source, ()
    return _snapshot_sibling_closure(source, tree, name, bound_tools, boundary)


def bind_executable(source, tree, name, bound_tools, boundary):
    prefix = source.read_prefix()
    if not prefix.startswith(b"#!"):
        if not source.trusted_system_route():
            raise SetupError(
                "a non-system executable requires an immutable runtime manifest"
            )
        execution, dependencies = execution_tool(
            source, tree, name, bound_tools, boundary
        )
        return BoundExecutable(source, execution, boundary, dependencies=dependencies)
    line, separator, _remainder = prefix.partition(b"\n")
    if not separator:
        raise SetupError("executable shebang exceeds the allowed size")
    try:
        parts = shlex.split(os.fsdecode(line[2:].strip()), posix=True)
    except ValueError as error:
        raise SetupError("executable has an invalid shebang") from error
    if len(parts) != 1 or not os.path.isabs(parts[0]):
        raise SetupError("executable shebang must name one direct absolute interpreter")
    interpreter_path = os.path.realpath(parts[0])
    interpreter_source = BoundTool.open(interpreter_path)
    bound_tools.append(interpreter_source)
    if not interpreter_source.trusted_system_route():
        raise SetupError("a mutable interpreter/runtime closure is not supported")
    if interpreter_source.read_prefix().startswith(b"#!"):
        raise SetupError("nested executable interpreters are not supported")
    execution, dependencies = execution_tool(source, tree, name, bound_tools, boundary)
    interpreter_execution, interpreter_dependencies = execution_tool(
        interpreter_source,
        tree,
        name + "-interpreter",
        bound_tools,
        boundary,
    )
    return BoundExecutable(
        source,
        execution,
        boundary,
        interpreter_source,
        interpreter_execution,
        dependencies=dependencies + interpreter_dependencies,
    )


def hook_at(directory, name):
    try:
        os.stat(name, dir_fd=directory.descriptor, follow_symlinks=False)
    except FileNotFoundError:
        return None
    return BoundFile.open(name, directory_fd=directory.descriptor)


def canonical_generated_hook(data, hook_type, install_python):
    """Replace generator-owned shell text with one installer-owned assignment."""

    if (
        not isinstance(install_python, str)
        or not os.path.isabs(install_python)
        or "\x00" in install_python
        or "\n" in install_python
        or "\r" in install_python
    ):
        raise SetupError("INSTALL_PYTHON must be one direct absolute path")
    try:
        lines = tuple(data.decode("utf-8").splitlines())
    except UnicodeDecodeError as error:
        raise SetupError("pre-commit generated a non-UTF-8 hook") from error
    expected_args = (
        "ARGS=(hook-impl --config=.pre-commit-config.yaml --hook-type={})".format(
            hook_type
        )
    )
    if len(lines) != 20 or lines[:5] != HEADER or lines[7:] != TAIL:
        raise SetupError("pre-commit generated an invalid {} hook".format(hook_type))
    if lines[6] != expected_args:
        raise SetupError("pre-commit generated an invalid {} hook".format(hook_type))
    canonical = (
        *HEADER,
        "INSTALL_PYTHON=" + shlex.quote(install_python),
        expected_args,
        *TAIL,
    )
    return ("\n".join(canonical) + "\n").encode("utf-8")


def generated(data, hook_type, install_python=None):
    try:
        lines = tuple(data.decode("utf-8").splitlines())
        assignment = shlex.split(lines[5], posix=True) if len(lines) == 20 else []
    except (UnicodeDecodeError, ValueError):
        return False
    expected_assignment = (
        "INSTALL_PYTHON=" + install_python if install_python is not None else None
    )
    return (
        lines[:5] == HEADER
        and lines[7:] == TAIL
        and len(assignment) == 1
        and assignment[0].startswith("INSTALL_PYTHON=/")
        and (expected_assignment is None or assignment[0] == expected_assignment)
        and lines[6]
        == "ARGS=(hook-impl --config=.pre-commit-config.yaml --hook-type={})".format(
            hook_type
        )
    )


def inventory(directory):
    result = {}
    names = sorted(os.listdir(directory.descriptor))
    for name in names:
        item = hook_at(directory, name)
        if item is None:
            raise SetupError("hook inventory changed while reading")
        if stat.S_IMODE(item.token[2]) & ~0o777:
            raise SetupError("hook entry has unsafe mode: {}".format(name))
        result[name] = item
    if names != sorted(os.listdir(directory.descriptor)):
        raise SetupError("hook inventory changed while reading")
    return result


def content(items):
    return {
        name: (item.data, stat.S_IMODE(item.token[2])) for name, item in items.items()
    }


def atomic_rename(parent_fd, source, destination, exchange=False):
    libc = ctypes.CDLL(None, use_errno=True)
    if sys.platform.startswith("linux"):
        function = getattr(libc, "renameat2", None)
        flag = 2 if exchange else 1
    elif sys.platform == "darwin":
        function = getattr(libc, "renameatx_np", None)
        flag = 0x2 if exchange else 0x4
    else:
        function = None
    if function is None:
        raise SetupError("atomic hook-directory rename is unsupported on this platform")
    function.argtypes = (
        ctypes.c_int,
        ctypes.c_char_p,
        ctypes.c_int,
        ctypes.c_char_p,
        ctypes.c_uint,
    )
    function.restype = ctypes.c_int
    ctypes.set_errno(0)
    if (
        function(
            parent_fd, os.fsencode(source), parent_fd, os.fsencode(destination), flag
        )
        != 0
    ):
        value = ctypes.get_errno()
        raise SetupError(
            "atomic hook-directory rename failed: {}".format(os.strerror(value))
        )


def full_manifest(items):
    return {name: (item.token, item.data) for name, item in items.items()}


def manifest_digest(items):
    """Return a stable digest for names, modes, and bytes in one directory."""

    digest = hashlib.sha256()
    for name, (data, mode) in sorted(items.items()):
        encoded = os.fsencode(name)
        for value in (encoded, str(mode).encode("ascii"), data):
            digest.update(len(value).to_bytes(8, "big"))
            digest.update(value)
    return digest.hexdigest()


def route_receipt(label, path, token, items):
    return "{} {} identity={}:{} digest=sha256:{}".format(
        label,
        shlex.quote(path),
        token[0],
        token[1],
        manifest_digest(items),
    )


def write_entry(directory, name, data, mode):
    if not name or name in (".", "..") or os.sep in name:
        raise SetupError("invalid hook entry name")
    flags = (
        os.O_RDWR
        | os.O_CREAT
        | os.O_EXCL
        | os.O_CLOEXEC
        | os.O_NOFOLLOW
        | os.O_NONBLOCK
    )
    descriptor = os.open(name, flags, 0o600, dir_fd=directory.descriptor)
    try:
        write_all(descriptor, data)
        os.fsync(descriptor)
        os.fchmod(descriptor, mode)
        os.fsync(descriptor)
        if read_fd(descriptor) != data:
            raise SetupError("hook candidate readback failed: {}".format(name))
    finally:
        os.close(descriptor)


@dataclass
class Candidate:
    name: str
    path: str
    directory: BoundDir
    items: dict

    @property
    def token(self):
        return self.directory.token

    @property
    def receipt(self):
        return route_receipt("candidate", self.path, self.token, content(self.items))

    def close(self):
        self.directory.close()


def make_candidate(repo, desired):
    name = ".odysseus-hooks-{}".format(secrets.token_hex(24))
    path = os.path.join(repo.common.path, name)
    created = False
    directory = None
    try:
        os.mkdir(name, 0o700, dir_fd=repo.common.descriptor)
        created = True
        directory = BoundDir.open_at(repo.common.descriptor, name, path)
        mode = stat.S_IMODE(repo.hooks.token[2]) if repo.hooks is not None else 0o755
        os.fchmod(directory.descriptor, mode)
        directory.token = dir_ident(os.fstat(directory.descriptor))
        directory.verify()
        for entry_name, (data, mode) in sorted(desired.items()):
            write_entry(directory, entry_name, data, mode)
        os.fsync(directory.descriptor)
        actual = inventory(directory)
        if content(actual) != desired:
            raise SetupError("completed hook candidate does not match the plan")
        candidate = Candidate(name, path, directory, actual)
        directory = None
        return candidate
    except BaseException as error:
        if directory is not None:
            try:
                token = dir_ident(os.fstat(directory.descriptor))
                try:
                    items = content(inventory(directory))
                    receipt = route_receipt("candidate", path, token, items)
                except BaseException:
                    receipt = "candidate {} identity={}:{}".format(
                        shlex.quote(path), token[0], token[1]
                    )
            finally:
                directory.close()
            raise SetupError(
                "hook candidate preparation failed; preserved {}; error: {}".format(
                    receipt, error
                )
            ) from error
        if created:
            raise SetupError(
                "hook candidate binding failed; preserved unbound route {}: {}".format(
                    path, error
                )
            ) from error
        raise


def configs_under(root):
    def reject_walk_error(error):
        raise SetupError("cannot inventory pre-commit configurations: {}".format(error))

    result = []
    for current, dirs, files in os.walk(
        root, topdown=True, onerror=reject_walk_error, followlinks=False
    ):
        rel = os.path.relpath(current, root)
        depth = 0 if rel == "." else rel.count(os.sep) + 1
        dirs[:] = sorted(
            name
            for name in dirs
            if name != ".git"
            and depth < 2
            and not os.path.islink(os.path.join(current, name))
        )
        if ".pre-commit-config.yaml" in files:
            result.append(os.path.join(current, ".pre-commit-config.yaml"))
    return sorted(result, key=os.fsencode)


def git_value(git, repo, args, env, timeout):
    result = run([git, "-C", repo] + list(args), "/", env, timeout)
    require_ok("git {}".format(" ".join(args)), result)
    return result[1].decode("utf-8", "strict").strip()


def _single_metadata_path(data, label):
    try:
        value = data.decode("utf-8", "strict")
    except UnicodeError as error:
        raise SetupError("{} is not UTF-8".format(label)) from error
    if not value or "\x00" in value or "\n" in value or "\r" in value:
        raise SetupError("{} must contain one path".format(label))
    return value


def _bind_repository_metadata(directory, path):
    """Bind Git metadata from filesystem objects, independent of Git output."""

    git_entry = os.stat(".git", dir_fd=directory.descriptor, follow_symlinks=False)
    opened = []
    try:
        if stat.S_ISDIR(git_entry.st_mode):
            git_path = os.path.join(path, ".git")
            git_dir = BoundDir.open_at(
                directory.descriptor, ".git", git_path, safe=True
            )
        elif stat.S_ISREG(git_entry.st_mode):
            pointer = BoundFile.open(".git", directory_fd=directory.descriptor)
            line = _single_metadata_path(pointer.data.rstrip(b"\n"), ".git file")
            prefix = "gitdir: "
            if not line.startswith(prefix) or not line[len(prefix) :]:
                raise SetupError(".git file has an invalid gitdir record")
            raw = line[len(prefix) :]
            git_path = os.path.abspath(
                raw if os.path.isabs(raw) else os.path.join(path, raw)
            )
            git_dir = BoundDir.open(git_path, safe=True)
        else:
            raise SetupError(".git is not a direct directory or gitfile")
        opened.append(git_dir)

        try:
            common_file = BoundFile.open("commondir", directory_fd=git_dir.descriptor)
        except SetupError as error:
            cause = error.__cause__
            if not isinstance(cause, FileNotFoundError) and "No such file" not in str(
                error
            ):
                raise
            common_path = git_dir.path
        else:
            raw = _single_metadata_path(common_file.data.rstrip(b"\n"), "Git commondir")
            common_path = os.path.abspath(
                raw if os.path.isabs(raw) else os.path.join(git_dir.path, raw)
            )
        common = BoundDir.open(common_path, safe=True)
        opened.append(common)
        return git_dir, common
    except BaseException:
        for value in reversed(opened):
            value.close()
        raise


@dataclass
class Repo:
    path: str
    label: str
    config: BoundFile
    directory: BoundDir
    git_dir: BoundDir
    common: BoundDir
    hooks: BoundDir
    before: dict

    def close(self):
        for value in (self.hooks, self.common, self.git_dir, self.directory):
            if value is not None:
                value.close()


def bind_repo(root, config_path, git, env, timeout):
    path = os.path.dirname(config_path)
    opened = []
    try:
        directory = BoundDir.open(path)
        opened.append(directory)
        config = BoundFile.open(
            ".pre-commit-config.yaml", directory_fd=directory.descriptor
        )
        git_dir, common = _bind_repository_metadata(directory, path)
        opened.extend((git_dir, common))
        top = os.path.realpath(
            git_value(git, path, ["rev-parse", "--show-toplevel"], env, timeout)
        )
        if top != os.path.realpath(path) or not (
            top == root or top.startswith(root + os.sep)
        ):
            raise SetupError("configuration is not at a Git top level")
        reported_git_path = os.path.realpath(
            git_value(git, path, ["rev-parse", "--absolute-git-dir"], env, timeout)
        )
        common_raw = git_value(
            git, path, ["rev-parse", "--git-common-dir"], env, timeout
        )
        reported_common_path = os.path.realpath(
            common_raw if os.path.isabs(common_raw) else os.path.join(path, common_raw)
        )
        if reported_git_path != git_dir.path or reported_common_path != common.path:
            raise SetupError(
                "Git metadata output disagrees with independently bound filesystem metadata"
            )
        configured = run(
            [git, "-C", path, "config", "--show-origin", "--get", "core.hooksPath"],
            "/",
            env,
            timeout,
        )
        if configured[0] == 0:
            raise SetupError("core.hooksPath is not supported")
        if configured[0] != 1:
            require_ok("git config core.hooksPath", configured)
        hooks_path = os.path.join(common.path, "hooks")
        hooks = None
        before = {}
        try:
            os.stat("hooks", dir_fd=common.descriptor, follow_symlinks=False)
        except FileNotFoundError:
            pass
        else:
            hooks = BoundDir.open_at(common.descriptor, "hooks", hooks_path)
            opened.append(hooks)
            before = inventory(hooks)
        label = "." if path == root else os.path.relpath(path, root)
        return Repo(path, label, config, directory, git_dir, common, hooks, before)
    except BaseException:
        for value in reversed(opened):
            value.close()
        raise


def shadow_repo(tree, name, config, git, env, timeout):
    path = tree.mkdir(name)
    result = run(
        [git, "-c", "init.templateDir=", "init", "-q", path], "/", env, timeout
    )
    require_ok("isolated git init", result)
    target = os.path.join(path, ".pre-commit-config.yaml")
    descriptor = os.open(
        target,
        os.O_RDWR
        | os.O_CREAT
        | os.O_EXCL
        | os.O_CLOEXEC
        | os.O_NOFOLLOW
        | os.O_NONBLOCK,
        0o600,
    )
    try:
        write_all(descriptor, config.data)
        os.fsync(descriptor)
        if read_fd(descriptor) != config.data:
            raise SetupError("private configuration readback failed")
    finally:
        os.close(descriptor)
    return path, BoundFile.open(target)


def generated_inventory(path, install_python=None):
    directory = BoundDir.open(path, safe=True)
    try:
        result = {}
        for hook_type in HOOK_TYPES:
            item = hook_at(directory, hook_type)
            if item is not None:
                if not item.executable or not generated(item.data, hook_type):
                    raise SetupError(
                        "pre-commit generated an invalid {} hook".format(hook_type)
                    )
                result[hook_type] = (
                    canonical_generated_hook(item.data, hook_type, install_python)
                    if install_python is not None
                    else item.data
                )
        unexpected = [
            name
            for name in os.listdir(directory.descriptor)
            if not name.endswith(".sample") and name not in result
        ]
        if unexpected:
            raise SetupError("pre-commit generated an unexpected hook entry")
        return result
    finally:
        directory.close()


def _hook_python_path(pre_commit):
    interpreter = pre_commit.interpreter_source
    if interpreter is None:
        return "/__odysseus_no_install_python__"
    basename = os.path.basename(interpreter.path)
    if re.fullmatch(r"python(?:[0-9]+(?:\.[0-9]+)*)?", basename):
        return interpreter.path
    return "/__odysseus_no_install_python__"


def generate(repo, tree, index, pre_commit, git, env, timeout, install):
    shadow, config = shadow_repo(
        tree, "repo-{}".format(index), repo.config, git, env, timeout
    )
    result = run(
        [pre_commit, "validate-config", ".pre-commit-config.yaml"], shadow, env, timeout
    )
    config.verify()
    require_ok("pre-commit validate-config", result)
    result = run([pre_commit, "install"], shadow, env, timeout)
    config.verify()
    require_ok("pre-commit hook discovery", result)
    hooks_path = os.path.join(shadow, ".git", "hooks")
    install_python = _hook_python_path(pre_commit)
    discovered = generated_inventory(hooks_path, install_python)
    if not discovered:
        raise SetupError("pre-commit discovered no install hook types")
    if not install:
        return set(discovered), discovered
    for name in discovered:
        os.unlink(os.path.join(hooks_path, name))
    command = [pre_commit, "install", "--install-hooks"]
    for name in sorted(discovered):
        command.extend(("--hook-type", name))
    result = run(command, shadow, env, timeout)
    config.verify()
    require_ok("pre-commit install", result)
    actual = generated_inventory(hooks_path, install_python)
    if set(actual) != set(discovered):
        raise SetupError("actual hook inventory differs from discovery")
    return set(discovered), actual


def named_inventory(repo, name="hooks"):
    path = os.path.join(repo.common.path, name)
    relative = BoundDir.open_at(repo.common.descriptor, name, path)
    absolute = None
    try:
        absolute = BoundDir.open(path, safe=True)
        left = inventory(relative)
        right = inventory(absolute)
        if relative.token != absolute.token or full_manifest(left) != full_manifest(
            right
        ):
            raise SetupError("named hook-directory routes disagree: {}".format(path))
        return relative, left
    except BaseException:
        relative.close()
        raise
    finally:
        if absolute is not None:
            absolute.close()


def require_absent(repo, name="hooks"):
    path = os.path.join(repo.common.path, name)
    for check in ((name, repo.common.descriptor), (path, None)):
        try:
            os.stat(check[0], dir_fd=check[1], follow_symlinks=False)
        except FileNotFoundError:
            continue
        raise SetupError("unexpected hook directory appeared: {}".format(path))


def base_routes(repo):
    repo.directory.verify()
    repo.config.verify()
    repo.git_dir.verify()
    repo.common.verify()


def preflight(repo):
    base_routes(repo)
    if repo.hooks is None:
        require_absent(repo)
        return
    repo.hooks.verify()
    current, items = named_inventory(repo)
    try:
        if current.token != repo.hooks.token or full_manifest(items) != full_manifest(
            repo.before
        ):
            raise SetupError("live hook inventory changed during private generation")
    finally:
        current.close()


def desired_hooks(repo, expected, payloads, native, root):
    desired = content(repo.before)
    for name, item in repo.before.items():
        if name in HOOK_TYPES and generated(item.data, name) and name not in expected:
            desired.pop(name)
    for name in expected:
        item = repo.before.get(name)
        if item is not None and not generated(item.data, name):
            migratable = (
                repo.path == root
                and name == "pre-push"
                and item.executable
                and item.data == native.data
            )
            if not migratable:
                raise SetupError("unmanaged {} hook already exists".format(name))
        desired[name] = (payloads[name], 0o755)
    if repo.path == root:
        legacy = repo.before.get("pre-push.legacy")
        if legacy is not None and (not legacy.executable or legacy.data != native.data):
            raise SetupError("unmanaged legacy pre-push hook already exists")
        desired["pre-push.legacy"] = (native.data, stat.S_IMODE(native.token[2]))
    return desired


def verify(repo, expected, payloads, native, root, desired=None):
    directory, items = named_inventory(repo)
    try:
        if desired is not None and content(items) != desired:
            raise SetupError("installed hook directory differs from the committed plan")
        for name in HOOK_TYPES:
            item = items.get(name)
            if name in expected:
                if item is None or not item.executable or item.data != payloads[name]:
                    raise SetupError("installed managed hook inventory is not exact")
            elif item is not None and generated(item.data, name):
                raise SetupError(
                    "stale generated hook remains installed: {}".format(name)
                )
        if repo.path == root:
            legacy = items.get("pre-push.legacy")
            if legacy is None or not legacy.executable or legacy.data != native.data:
                raise SetupError("signed pre-push boundary is not installed")
    finally:
        directory.close()


class DirectoryLock:
    """Hold a bounded advisory lock on an already bound directory."""

    def __init__(self, descriptor, timeout=2.0):
        self.descriptor = descriptor
        self.locked = False
        deadline = time.monotonic() + timeout
        while True:
            try:
                fcntl.flock(descriptor, fcntl.LOCK_EX | fcntl.LOCK_NB)
                self.locked = True
                return
            except OSError as error:
                if error.errno not in (errno.EACCES, errno.EAGAIN):
                    raise SetupError(
                        "cannot lock the Git common directory: {}".format(error)
                    ) from error
                if time.monotonic() >= deadline:
                    raise SetupError(
                        "timed out while locking the Git common directory"
                    ) from error
                time.sleep(0.02)

    def close(self):
        if not self.locked:
            return
        self.locked = False
        fcntl.flock(self.descriptor, fcntl.LOCK_UN)


def route_token(repo, name):
    try:
        value = os.stat(name, dir_fd=repo.common.descriptor, follow_symlinks=False)
    except FileNotFoundError:
        return None
    return dir_ident(value)


def publication_receipts(repo, candidate, desired):
    active_path = os.path.join(repo.common.path, "hooks")
    active, active_items = named_inventory(repo)
    try:
        if active.token != candidate.token or content(active_items) != desired:
            raise SetupError(
                "the active hook route does not name the committed candidate"
            )
        receipts = [
            route_receipt("active", active_path, active.token, content(active_items))
        ]
    finally:
        active.close()

    if repo.hooks is not None:
        recovery, recovery_items = named_inventory(repo, candidate.name)
        try:
            expected = content(repo.before)
            if (
                recovery.token != repo.hooks.token
                or content(recovery_items) != expected
            ):
                raise SetupError(
                    "the recovery hook route does not name the displaced directory"
                )
            receipts.append(
                route_receipt(
                    "recovery", candidate.path, recovery.token, content(recovery_items)
                )
            )
        finally:
            recovery.close()
    return "; ".join(receipts)


def best_effort_publication_receipts(repo, candidate, desired):
    try:
        return publication_receipts(repo, candidate, desired)
    except BaseException as error:
        active_path = os.path.join(repo.common.path, "hooks")
        owned = content(inventory(candidate.directory))
        details = route_receipt("expected-active", active_path, candidate.token, owned)
        if repo.hooks is not None:
            recovered = content(inventory(repo.hooks))
            details += "; " + route_receipt(
                "expected-recovery", candidate.path, repo.hooks.token, recovered
            )
        return "{}; route verification error: {}".format(details, error)


def install(repo, expected, payloads, native, root, guard):
    desired = desired_hooks(repo, expected, payloads, native, root)
    candidate = make_candidate(repo, desired)
    lock = None
    committed = False
    try:
        lock = DirectoryLock(repo.common.descriptor)
        guard()
        preflight(repo)
        if (
            dir_ident(os.fstat(candidate.directory.descriptor)) != candidate.token
            or content(inventory(candidate.directory)) != desired
            or route_token(repo, candidate.name) != candidate.token
        ):
            raise SetupError("hook candidate changed before publication")

        # Recheck all live inputs while the common-directory lock is held.  The
        # atomic rename below is the only publication commit point.
        guard()
        preflight(repo)
        rename_error = None
        try:
            atomic_rename(
                repo.common.descriptor,
                candidate.name,
                "hooks",
                exchange=repo.hooks is not None,
            )
        except BaseException as error:
            rename_error = error

        committed = route_token(repo, "hooks") == candidate.token
        if not committed:
            if rename_error is not None:
                raise rename_error
            raise SetupError(
                "atomic hook-directory rename returned without publishing the candidate"
            )

        os.fsync(repo.common.descriptor)
        guard()
        receipts = publication_receipts(repo, candidate, desired)
        verify(repo, expected, payloads, native, root, desired)
        if rename_error is not None:
            raise SetupError(
                "atomic rename reported an error after publication: {}".format(
                    rename_error
                )
            )
        emit("ACTION", "hook publication committed; {}".format(receipts))
        return desired
    except BaseException as error:
        if committed:
            receipts = best_effort_publication_receipts(repo, candidate, desired)
            raise SetupError(
                "hook publication committed and was not rolled back; {}; error: {}".format(
                    receipts, error
                )
            ) from error
        raise SetupError(
            "hook publication did not commit; preserved {}; error: {}".format(
                candidate.receipt, error
            )
        ) from error
    finally:
        if lock is not None:
            lock.close()
        candidate.close()


def arguments(argv):
    parser = argparse.ArgumentParser()
    parser.add_argument("--root", required=True)
    parser.add_argument("--pre-commit", required=True)
    parser.add_argument("--git", required=True)
    parser.add_argument("--mode", choices=("check", "install"), required=True)
    parser.add_argument("--expected-version")
    parser.add_argument("--timeout", type=float, default=300)
    return parser.parse_args(argv)


def main(argv):
    args = arguments(argv)
    failures = 0
    tree = None
    root_dir = None
    execution_tree = None
    bound_tools = []
    try:
        if not math.isfinite(args.timeout):
            raise SetupError("timeout must be finite")
        if args.timeout <= 0 or args.timeout > 1800:
            raise SetupError("timeout must be in (0, 1800]")
        root = os.path.realpath(args.root)
        if root != os.path.abspath(args.root):
            raise SetupError("Odysseus root must be a direct absolute path")
        root_dir = BoundDir.open(root)
        native = BoundFile.open(
            os.path.join(root, ".githooks", "pre-push"), executable=True
        )
        pre_commit_path = os.path.realpath(args.pre_commit)
        git_path = os.path.realpath(args.git)
        pre_commit_source = BoundTool.open(pre_commit_path)
        bound_tools.append(pre_commit_source)
        git_source = BoundTool.open(git_path)
        bound_tools.append(git_source)
        tree = PrivateTree()
        home = tree.mkdir("home")
        cache = tree.mkdir("cache")
        execution_tree = PrivateTree()
        boundary = ReadOnlyExecutionBoundary(execution_tree, tree, bound_tools)
        boundary.require()
        pre_commit = bind_executable(
            pre_commit_source,
            execution_tree,
            "pre-commit",
            bound_tools,
            boundary,
        )
        git = bind_executable(git_source, execution_tree, "git", bound_tools, boundary)
        env = clean_env(pre_commit, git, home, cache)

        def verify_tools():
            tree.verify()
            boundary.verify()
            for tool in bound_tools:
                tool.verify()

        verify_tools()
        result = run([pre_commit, "--version"], "/", env, args.timeout)
        verify_tools()
        require_ok("pre-commit version probe", result)
        match = VERSION.fullmatch(result[1].decode("utf-8", "replace").strip())
        if not match:
            raise SetupError("pre-commit returned an unrecognized version")
        version = match.group(1)
        if args.expected_version and args.expected_version != version:
            raise SetupError(
                "expected pre-commit {}, found {}".format(
                    args.expected_version, version
                )
            )
        emit("PASS", "pre-commit {}".format(version))
        configs = configs_under(root)
        if not configs:
            emit("WARN", "No .pre-commit-config.yaml files found under {}".format(root))
        for index, config_path in enumerate(configs):
            repo = None
            terminal_error = None
            label = os.path.relpath(os.path.dirname(config_path), root)
            try:
                root_dir.verify()
                native.verify()
                verify_tools()
                repo = bind_repo(root, config_path, git, env, args.timeout)
                label = repo.label
                expected, payloads = generate(
                    repo,
                    tree,
                    index,
                    pre_commit,
                    git,
                    env,
                    args.timeout,
                    args.mode == "install",
                )
                if repo.path == root and "pre-push" not in expected:
                    raise SetupError("root configuration must install pre-push")

                def guard():
                    root_dir.verify()
                    native.verify()
                    verify_tools()
                    base_routes(repo)

                guard()
                desired = None
                if args.mode == "install":
                    emit("ACTION", "pre-commit install: {}".format(label))
                    desired = install(repo, expected, payloads, native, root, guard)
                else:
                    preflight(repo)
                guard()
                verify(repo, expected, payloads, native, root, desired)
                message = (
                    "pre-commit and signed pre-push hooks installed"
                    if repo.path == root
                    else "hooks installed"
                )
                emit("PASS", "pre-commit: {} — {}".format(label, message))
            except CancellationError as error:
                terminal_error = error
                raise
            except (OSError, SetupError, UnicodeError) as error:
                failures += 1
                emit("FAIL", "pre-commit: {} — {}".format(label, error))
            finally:
                if repo is not None:
                    try:
                        repo.close()
                    except BaseException as error:
                        if terminal_error is not None:
                            raise terminal_error from error
                        raise
    except CancellationError as error:
        failures += 1
        emit("FAIL", error)
    except (OSError, SetupError, UnicodeError) as error:
        failures += 1
        emit("FAIL", error)
    finally:
        if root_dir is not None:
            root_dir.close()
        for tool in reversed(bound_tools):
            tool.close()
        if execution_tree is not None:
            problem = execution_tree.close()
            if problem:
                failures += 1
                emit("FAIL", problem)
        if tree is not None:
            problem = tree.close()
            if problem:
                failures += 1
                emit("FAIL", problem)
    return 1 if failures else 0


if __name__ == "__main__":
    raise SystemExit(main(sys.argv[1:]))
